---
title: 'Applied: survey data'
author: "Lina Walkowiak, Lelia Corfitsen"
date: "2023-03-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load("tidyverse", "dplyr", "car", "lme4")
rm()

```


```{r}
df <- read.csv("//Users/lina/Documents/data_may.csv")

df <- df[,- c(1, 2, 4, 5, 6, 15, 16)]

df <- rename(df, id = REF, r_perception = EN01_01, r_expertise = EN01_02, r_mental = EN01_03, r_attention = EN01_04, memory=EN02_01, age = IN02, gender = IN03, cogsci = IN05, p1 = SD01_01, e1 = SD02_01, m1 = SD03_01, a1 = SD04_01, p0 = SE01_01, e0 = SE02_01, m0 = SE03_01, a0 = SE04_01, p2 =SI01_01, e2 =SI02_01, m2 = SI03_01, a2= SI04_01, p3 =SL01_01, e3 = SL02_01, m3= SL03_01, a3 = SL04_01)

```

```{r}

df_new0 <-  mutate(df, avg0 = select(df, matches('0')) %>% rowMeans(na.rm=T))
df_new1 <-  mutate(df, avg1 = select(df, matches('1')) %>% rowMeans(na.rm=T))
df_new2 <-  mutate(df, avg2 = select(df, matches('2')) %>% rowMeans(na.rm=T))
df_new3 <-  mutate(df, avg3 = select(df, matches('3')) %>% rowMeans(na.rm=T))

df_all <- mutate(df, avg0 = select(df, matches('0')) %>% rowMeans(na.rm=T), avg1 = select(df, matches('1')) %>% rowMeans(na.rm=T),  avg2 = select(df, matches('2')) %>% rowMeans(na.rm=T), avg3 = select(df, matches('3')) %>% rowMeans(na.rm=T))


df_all <- df_all %>%
  mutate_at(vars(matches('^p[0-3]+$')), as.numeric) %>%
  mutate(avg_p = rowMeans(select(., matches('^p[0-3]+$')), na.rm = TRUE), avg_e = rowMeans(select(., matches('^e[0-3]+$')), na.rm = TRUE), avg_m = rowMeans(select(., matches('^m[0-3]+$')), na.rm = TRUE), avg_a = rowMeans(select(., matches('^a[0-3]+$')), na.rm = TRUE))

df_new0 <- df_new0[, c(1, 2,3, 4, 5, 6, 7,8,9,34)]
df_new0$slides <- '0'
df_new0 <- rename(df_new0, rating = avg0)
df_new0 <- cbind(df_new0)


df_new1 <- df_new1[, c(1, 2,3, 4, 5, 6, 7,8,9,34)]
df_new1$slides <- '1'
df_new1 <- rename(df_new1,rating = avg1)
df_new1 <- cbind(df_new1)


df_new2 <- df_new2[, c(1, 2,3, 4, 5, 6, 7,8,9,34)]
df_new2$slides <- '2'
df_new2 <- rename(df_new2, rating = avg2)
df_new2 <- cbind(df_new2)

df_new3 <- df_new3[, c(1, 2,3, 4, 5, 6, 7,8,9,34)]
df_new3$slides <- '3'
df_new3 <- rename(df_new3,rating = avg3)
df_new3 <- cbind(df_new3)
```


```{r}
df_new_p <- df %>%
  mutate_at(vars(matches('^p[0-3]+$')), as.numeric) %>%
  mutate(avg_p = rowMeans(select(., matches('^p[0-3]+$')), na.rm = TRUE))
df_new_p$topic <- 'perception'
df_new_p <- select(df_new_p,  topic)


df_new_e <- df %>%
  mutate_at(vars(matches('^e[0-3]+$')), as.numeric) %>%
  mutate(avg_e = rowMeans(select(., matches('^e[0-3]+$')), na.rm = TRUE))
df_new_e$topic <- 'expertise'
df_new_e <- select(df_new_e,  topic)

df_new_m <- df %>%
  mutate_at(vars(matches('^m[0-3]+$')), as.numeric) %>%
  mutate(avg_m = rowMeans(select(., matches('^m[0-3]+$')), na.rm = TRUE))
df_new_m$topic <- 'mental'
df_new_m <- select(df_new_m, topic)

df_new_a <- df %>%
  mutate_at(vars(matches('^a[0-3]+$')), as.numeric) %>%
  mutate(avg_a = rowMeans(select(., matches('^a[0-3]+$')), na.rm = TRUE))
df_new_a$topic <- 'attention'
df_new_a <- select(df_new_a,  topic)

df_interest <- cbind(df_new_p, df_new_e, df_new_m, df_new_a)

```


```{r}

df_new0 <-  mutate(df, avg0 = select(df, matches('0')) %>% rowMeans(na.rm=T))
df_new1 <-  mutate(df, avg1 = select(df, matches('1')) %>% rowMeans(na.rm=T))
df_new2 <-  mutate(df, avg2 = select(df, matches('2')) %>% rowMeans(na.rm=T))
df_new3 <-  mutate(df, avg3 = select(df, matches('3')) %>% rowMeans(na.rm=T))

df_new0 <- df_new0[, c(1, 2,3, 4, 5, 6, 7,8,9,34)]
df_new0$slides <- '0'
df_new0 <- rename(df_new0, rating = avg0)
df_new0 <- cbind(df_new0, df_interest)


df_new1 <- df_new1[, c(1, 2,3, 4, 5, 6, 7,8,9,34)]
df_new1$slides <- '1'
df_new1 <- rename(df_new1,rating = avg1)
df_new1 <- cbind(df_new1, df_interest)


df_new2 <- df_new2[, c(1, 2,3, 4, 5, 6, 7,8,9,34)]
df_new2$slides <- '2'
df_new2 <- rename(df_new2, rating = avg2)
df_new2 <- cbind(df_new2, df_interest)

df_new3 <- df_new3[, c(1, 2,3, 4, 5, 6, 7,8,9,34)]
df_new3$slides <- '3'
df_new3 <- rename(df_new3,rating = avg3)
df_new3 <- cbind(df_new3, df_interest)
```


```{r}
data <- rbind(df_new0, df_new1, df_new2, df_new3)
```

```{r}
write.csv(data, "//Users/lina/documents/cognitive_slides_data.csv", row.names=FALSE)
```




```{r}
# create a color palette
my_colors <- c("#FE3103", "#FE6907", "#FF9304", "#FFCD38")

# plot the data using ggplot
ggplot(data, aes(x = factor(slides), y = rating)) +
  geom_boxplot(fill = my_colors, color = "black", alpha = 0.7, outlier.shape = NA, ) +
  scale_fill_manual(values = my_colors) +
  labs(x = "Number of violated elements", y = "Rating", title = "Ratings of presented slides") +
  theme_bw() +
  theme(plot.title = element_text(size = 20, face = "bold"),
        axis.title = element_text(size = 10, face = "italic"),
        axis.text = element_text(size = 14),
        legend.position = "none")
```
```{r}
data$id <- as.numeric(data$id)
model1 <-  lm(rating~slides, data = data)
summary(model1)

```

```{r}
#plot(model1, which = 1)

ggplot(data.frame(residuals = resid(model1)), aes(x = residuals)) + 
  geom_histogram() +
  ggtitle("Histogram of Residuals")

#qqnorm(resid(model1), main = "Normal Q-Q Plot of Residuals")
#qqline(resid(model1))

#influenceIndexPlot(model1)


```



```{r}
mean(df$age)
range(df$age)
nrow(df[df$gender == '1', ]) # 1 = female 
nrow(df[df$gender == '2', ]) # 2 = male
nrow(df[df$gender == '3', ])
```


